[package]
name = "deps"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing-actix-web = { version = "0.7.9", features = ["opentelemetry_0_21"] }
tracing = { version = "0.1.35", default-features = false, features = ["std"] }
opentelemetry = { version = "0.21.0", default-features = false, features = ["trace", "logs"] }
opentelemetry_sdk = { version = "0.21.0", default-features = false, features = ["trace", "rt-tokio", "logs"] }
opentelemetry-semantic-conventions = "0.13.0"
opentelemetry-http = "0.10.0"
tracing-core = "0.1.28"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3.0", default-features = false, features = ["registry", "std", "fmt", "env-filter"] }
opentelemetry-otlp = { version = "0.14.0", features = ["metrics", "logs"] }
futures = "0.3.30"
serde = { version = "1.0", features = ["derive"] }
