[package]
name = "integ_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
otel-util = { path = "../../otel-util", version = "*" }
anyhow = "1"
testcontainers = "0.23.1"
